# Generated by Django 5.2.9 on 2026-01-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_profile_admin_comment_profile_proof_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='proof_document',
            new_name='verification_document',
        ),
    ]
