# Generated by Django 5.2.9 on 2026-01-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_rename_proof_document_profile_verification_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_document',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_status',
        ),
    ]
